name: the-box
include:
  - compose.app.yml
  - containers/compose.yml
  - containers/compose.web.yml
services:
  caddy:
    build:
      context: ./containers/caddy
      dockerfile: Dockerfile
    networks:
      - ingress
    pull_policy: build
