services:
  redis:
    image: redis:8.10.0-alpine
    volumes:
      - redis:/data
    networks:
      - app
      - caddy
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      - "caddy=redis.${HOSTNAME:-localhost}"
      - "caddy.respond=OK"
      - 'caddy_1.servers.listener_wrappers.0_layer4.@tls-redis=tls'
      - 'caddy_1.servers.listener_wrappers.0_layer4.@tls-redis.sni=redis.${HOSTNAME:-localhost}'
      - 'caddy_1.servers.listener_wrappers.0_layer4.route_1=@tls-redis'
      - 'caddy_1.servers.listener_wrappers.0_layer4.route_1.0_tls='
      - 'caddy_1.servers.listener_wrappers.0_layer4.route_1.1_proxy={{upstreams 6379}}'
      - 'caddy_1.servers.listener_wrappers.1_tls='
  web:
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis/
volumes:
  redis:
