services:
  caddy:
    image: codingjoe/the-box-caddy:main
    container_name: caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CADDY_INGRESS_NETWORKS: caddy
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:443:443/udp'
    networks:
      - caddy
      - caddy-wan
    command: [ "docker-proxy", "--caddyfile-path", "/etc/caddy/Caddyfile" ]
    restart: unless-stopped
    healthcheck:
      test: caddy validate --config /etc/caddy/Caddyfile
    labels:
      - "dev.dozzle.group=the-box"
    cap_add:
      - NET_ADMIN
    deploy:
      mode: global
networks:
  caddy:
    name: caddy
    internal: true
    external: false
  caddy-wan:
    name: caddy-wan
    internal: false
volumes:
  caddy_data:
  caddy_config:
