services:
  postgres:
    image: supabase/postgres:17.5.1.070-orioledb
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app
      - caddy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      - "caddy=pg.${HOSTNAME:-localhost}"
      - "caddy.respond=OK"
      - 'caddy_1.servers.listener_wrappers.0_layer4.@tls-pgsql=tls'
      - 'caddy_1.servers.listener_wrappers.0_layer4.@tls-pgsql.alpn=postgresql'
      - 'caddy_1.servers.listener_wrappers.0_layer4.@tls-pgsql.sni=pg.${HOSTNAME:-localhost}'
      - 'caddy_1.servers.listener_wrappers.0_layer4.route=@tls-pgsql'
      - 'caddy_1.servers.listener_wrappers.0_layer4.route.0_tls.connection_policy.alpn=postgresql'
      - 'caddy_1.servers.listener_wrappers.0_layer4.route.1_proxy={{upstreams 5432}}'
      - 'caddy_1.servers.listener_wrappers.1_tls='
  web:
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres/postgres
volumes:
  postgres:
