services:
  smtp:
    image: ghcr.io/docker-mailserver/docker-mailserver:16.0.0
    container_name: smtp
    volumes:
      - smtp-data:/var/mail
      - smtp-state:/var/mail-state
      - smtp-config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      SMTP_ONLY: 1
      ONE_DIR: 1
      # SSL is intentionally disabled for internal relay usage
      SSL_TYPE: ""
      PERMIT_DOCKER: connected-networks
      NETWORK_INTERFACE: eth1
      POSTFIX_INET_PROTOCOLS: ipv4
      LOG_LEVEL: info
    networks:
      app:
        interface_name: eth1
      smtp-wan:
        interface_name: eth0
    restart: always
    healthcheck:
      test: "ss --listening --ipv4 --tcp | grep --silent ':smtp' || exit 1"
      timeout: 3s
      interval: 10s
      retries: 5
      start_period: 30s
    labels:
      - "dev.dozzle.group=the-box"
    deploy:
      mode: global
    domainname: ${HOSTNAME}
    hostname: smtp
    stop_grace_period: 1m
  web:
    depends_on:
      smtp:
        condition: service_healthy
    environment:
      EMAIL_URL: smtp://smtp:25/
networks:
  smtp-wan:
    name: smtp-wan
volumes:
  smtp-config:
  smtp-state:
  smtp-data:
