services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.10-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - caddy_data:/data
      - caddy_config:/config
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - caddy
      - caddy-wan
    environment:
      CADDY_INGRESS_NETWORKS: caddy
    command: ["docker-proxy", "--caddyfile-path", "/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD-SHELL", "caddy validate --config /etc/caddy/Caddyfile"]
    deploy:
      mode: global
    labels:
      dev.dozzle.group: the-box
networks:
  caddy:
    name: caddy
    internal: true
    external: false
  caddy-wan:
volumes:
  caddy_data:
  caddy_config:
configs:
  caddyfile:
    content: |
      {
        cache

        log {
          output stdout
          format json
        }
      }

      :80, :443 {
        respond "Misdirected Request" 421
      }
