include:
  - compose.web.yml
services:
  redis:
    image: redis:8.6.0-alpine
    volumes:
      - redis:/data
    restart: unless-stopped
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    configs:
      - source: redis.conf
        target: /usr/local/etc/redis/redis.conf
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf"]
  web:
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis/
volumes:
  redis:
configs:
  redis.conf:
    content: |
      requirepass ${REDIS_PASSWORD}
