services:
  web:
    image: traefik/whoami:latest # placeholder image for OCI artifact
    memswap_limit: 1g # Limit total memory usage (RAM + swap) to 1GB
    stop_grace_period: 1m # Allow up to 1 minute for graceful shutdown
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.25' # Limit to 25% of a CPU
          memory: 512M # Limit to 512MB of RAM
    environment:
      PORT: ${PORT:-8000}
      HOSTNAME: ${HOSTNAME:-localhost}
    networks:
      - app
      - app-wan
      - caddy
    labels:
      caddy: ${HOSTNAME:-localhost}
      caddy.reverse_proxy: "{{upstreams ${PORT:-8000}}}"
      caddy.reverse_proxy.lb_policy: round_robin
      caddy.reverse_proxy.health_uri: /
      caddy.reverse_proxy.health_headers.X-Forwarded-Host: ${HOSTNAME:-localhost}
      caddy.reverse_proxy.health_headers.X-Forwarded-Proto: https
networks:
  app:
    driver: bridge
    internal: true
  app-wan:
    driver: bridge
  caddy:
    external: true
