version: "3.8"
services:
  caddy:
    container_name: caddy
    image: codingjoe/the-box-caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - caddy_data:/data
      - caddy_config:/config
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - caddy
      - caddy-wan
    environment:
      CADDY_INGRESS_NETWORKS: caddy
    command: ["docker-proxy", "--caddyfile-path", "/etc/caddy/Caddyfile"]
    healthcheck:
      test: caddy validate --config /etc/caddy/Caddyfile
    deploy:
      mode: global
    labels:
      - "dev.dozzle.group=the-box"
networks:
  caddy:
    name: caddy
    internal: true
    external: false
  caddy-wan:
    name: caddy-wan
    internal: false
volumes:
  caddy_data:
  caddy_config:
configs:
  caddyfile:
    file: ./Caddyfile
