include:
  - compose.web.yml
services:
  redis:
    image: valkey/valkey-bundle:9.0.0-alpine
    volumes:
      - redis:/data
    restart: unless-stopped
    environment:
      VALKEYCLI_AUTH: ${REDIS_PASSWORD}
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis/
volumes:
  redis:
