name: Deploy
on:
  workflow_run:
    workflows: [ci]
    strategy: wait-all
    timeout: 0
    branches: [main]
    types:
      - completed
  workflow_dispatch: # Allow manual trigger
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  paas:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: codingjoe/the-box/actions/deploy@main
        with:
          ssh-hosts: ${{ vars.SSH_HOSTNAME }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          hostname: ${{ vars.HOSTNAME }}
          dotenv-private-key: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
