name: Update The Box Deployment
description: 'Deploy the application to the production server using Docker Compose. This action connects to the production server via SSH, sets up a Docker context, and runs the necessary Docker Compose commands to deploy the application.'
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  ssh-host:
    description: 'The hostname or IP address of the production server (e.g., "example.com").'
    required: true
  ssh-known-hosts:
    description: 'The SSH known hosts entry for the production server (e.g., "github.com ssh-rsa ...").'
    required: true
  ssh-private-key:
    description: 'The SSH private key to use for connecting to the production server. This should be stored as a secret in the repository.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Pin known hosts
      run: |
        echo "::group::Pinning known hosts"
        echo "${{ inputs.ssh-known-hosts }}" >> ~/.ssh/known_hosts
        echo "::debug::Known hosts updated:"
        cat ~/.ssh/known_hosts
        echo "::endgroup::"
      shell: sh
    - name: Setting up Docker context for remote deployment
      run: |
        docker context create the-box --description "The Box" --docker "host=ssh://github@${{ inputs.ssh-host }}"
        docker context use the-box
      shell: sh
    - uses: codingjoe/the-box/actions/compose@main
    - name: Deploy application to the box
      run: docker compose --file oci://docker.io/codingjoe/the-box-caddy:latest --project-name the-box up --detach --quiet-pull
      shell: sh
