name: Delete Deployment
description: 'Delete the application deployment from the production server. This action will connect to the server via SSH, stop and remove the Docker containers associated with the application, and clean up any related resources. It uses the provided SSH credentials to securely access the server and execute the necessary commands to ensure a clean deletion of the deployment.'
branding:
  icon: 'sunset'
  color: 'red'
inputs:
  ssh-host:
    description: 'The hostname or IP address of the production server (e.g., "example.com").'
    required: true
  ssh-known-hosts:
    description: 'The SSH known hosts entry for the production server (e.g., "github.com ssh-rsa ...").'
    required: true
  ssh-private-key:
    description: 'The SSH private key to use for connecting to the production server. This should be stored as a secret in the repository.'
    required: true
  dotenv-private-key:
    description: 'The private key to use for decrypting secrets in the .env file on the production server. This should be stored as a secret in the repository.'
    required: true
  environment:
    description: 'The target environment of deployment (e.g., "production"). This will be used to determine which .env file to use and can also be used for environment-specific configurations.'
    required: true
  hostname:
    description: 'The domain of the application deployment (e.g., "example.com").'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Pin known hosts
      run: |
        echo "::group::Pinning known hosts"
        echo "${{ inputs.ssh-known-hosts }}" >> ~/.ssh/known_hosts
        echo "::debug::Known hosts updated:"
        cat ~/.ssh/known_hosts
        echo "::endgroup::"
      shell: sh
    - name: Setting up Docker context for remote deployment
      run: |
        docker context create the-box --description "The Box" --docker "host=ssh://github@${{ inputs.ssh-host }}"
        docker context use the-box
      shell: sh
    - uses: codingjoe/the-box/actions/compose@main
    - name: Install dotenvx
      shell: sh
      run: |
        curl -fsSL https://dotenvx.sh | sh
        cp .env.${{ inputs.environment }} .env
    - name: Delete application deployment from the box
      run: dotenvx run -- docker compose --file compose.${{ inputs.environment }}.yml --project-name ${{ github.ref_name }}  down --volumes
      shell: sh
      env:
        HOSTNAME: ${{ inputs.hostname }}
        DOTENV_PRIVATE_KEY: ${{ inputs.dotenv-private-key }}
